// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvfMKunsDlU0kQ05kMw1xXs6iRQzKXB3E',
    appId: '1:522106908587:web:078e5614331a99ff99ecee',
    messagingSenderId: '522106908587',
    projectId: 'calla-8888',
    authDomain: 'calla-8888.firebaseapp.com',
    storageBucket: 'calla-8888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjfMBu-50lAVTXVVWeL0mPuE6WEqYcW8',
    appId: '1:522106908587:android:7df6807eee49aa0299ecee',
    messagingSenderId: '522106908587',
    projectId: 'calla-8888',
    storageBucket: 'calla-8888.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvfMKunsDlU0kQ05kMw1xXs6iRQzKXB3E',
    appId: '1:522106908587:web:0aeda7656d83cff899ecee',
    messagingSenderId: '522106908587',
    projectId: 'calla-8888',
    authDomain: 'calla-8888.firebaseapp.com',
    storageBucket: 'calla-8888.firebasestorage.app',
  );
}
